import { v4 as uuidv4 } from 'uuid';

const VIBE_PROMPTS = {
  luxury: "Create an elegant, premium aesthetic with gold accents, serif fonts, and smooth animations.",
  modern: "Clean lines, minimalist design, bold typography, and subtle shadows.",
  playful: "Fun colors, rounded corners, bouncy animations, and friendly vibes.",
  tech: "Dark theme, neon accents, monospace fonts, and futuristic feel.",
  nature: "Earth tones, organic shapes, natural textures, and calming colors."
};

const COMPONENT_INFO = {
  assetUpload: { name: "Asset Upload", keywords: ["upload", "file", "document", "ipfs", "metadata"] },
  mintButton: { name: "Token Mint", keywords: ["mint", "tokenize", "nft", "create"] },
  listingGrid: { name: "Listing Grid", keywords: ["listing", "marketplace", "grid", "browse"] },
  nftPreview: { name: "NFT Preview", keywords: ["preview", "view", "image", "display"] },
  assetDetails: { name: "Asset Details", keywords: ["details", "info", "description", "specs"] },
  carousel: { name: "Image Carousel", keywords: ["carousel", "slider", "gallery", "slides"] },
  buyButton: { name: "Buy / Trade", keywords: ["buy", "purchase", "trade", "pay"] },
  pricingOracle: { name: "Price Oracle", keywords: ["price", "oracle", "valuation", "rate"] },
  analytics: { name: "Analytics", keywords: ["analytics", "stats", "charts", "metrics"] },
  auction: { name: "Auction Panel", keywords: ["auction", "bid", "timed sale"] },
  offer: { name: "Make Offer", keywords: ["offer", "bid", "negotiate"] },
  fractional: { name: "Fractional Share", keywords: ["fractional", "share", "split", "divide"] },
  royalties: { name: "Royalty Config", keywords: ["royalty", "creator fee", "revenue"] },
  transfer: { name: "Transfer Token", keywords: ["transfer", "send", "wallet"] },
  walletConnect: { name: "Wallet Connect", keywords: ["wallet", "connect", "metamask"] },
  qrCode: { name: "QR Code", keywords: ["qr", "code", "mobile", "scan"] },
  networkStatus: { name: "Network Status", keywords: ["network", "chain", "gas", "status"] },
  countdown: { name: "Countdown Timer", keywords: ["countdown", "timer", "time", "deadline"] },
  notifications: { name: "Notifications", keywords: ["notification", "alert", "activity"] },
  lockup: { name: "Token Lock", keywords: ["lock", "vesting", "schedule", "release"] },
};

const CONTRACT_TEMPLATES = {
  token: (description, vibeMode) => {
    const vibe = vibeMode ? `\n    // 🚀 Initializing token contract - let's make it rain! 💸\n    ` : '';
    return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC1155/ERC1155.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/token/ERC1155/extensions/ERC1155Supply.sol";
${vibe}
/**
 * RWA Token Contract
 * ${description}
 * Generated by RealFlow Studio AI
 */
contract RWAToken is ERC1155, Ownable, ERC1155Supply {
    uint256 public constant LAND = 0;
    uint256 public constant BUILDING = 1;
    
    mapping(uint256 => string) public tokenURIs;
    
    constructor() ERC1155("") Ownable(msg.sender) ${vibeMode ? '{\n        // Setting up the vibes! ✨' : '{'}
    }
    
    function setURI(uint256 id, string memory uri) external onlyOwner {
        tokenURIs[id] = uri;
    }
    
    function mintLand(address to, uint256 amount, string memory uri) 
        external onlyOwner 
    {
        _mint(to, LAND, amount, bytes(uri));
    }
    
    function mintBuilding(address to, uint256 amount, string memory uri) 
        external onlyOwner 
    {
        _mint(to, BUILDING, amount, bytes(uri));
    }
    
    function mintBatch(address to, uint256[] memory ids, uint256[] memory amounts, string[] memory uris)
        external onlyOwner
    {
        for (uint i = 0; i < ids.length; i++) {
            _mint(to, ids[i], amounts[i], bytes(uris[i]));
        }
    }
    
    function _beforeTokenTransfer(
        address operator,
        address from,
        address to,
        uint256[] memory ids,
        uint256[] memory amounts,
        bytes memory data
    ) internal override(ERC1155, ERC1155Supply) {
        super._beforeTokenTransfer(operator, from, to, ids, amounts, data);
    }
}`;
  },
  marketplace: (description, vibeMode) => {
    const vibe = vibeMode ? `\n    // 🎪 Marketplace vibes activated! Let's trade some assets! 🤝\n    ` : '';
    return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC1155/IERC1155.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
${vibe}
/**
 * Marketplace Contract
 * ${description}
 * Generated by RealFlow Studio AI
 */
contract Marketplace is Ownable {
    struct Listing {
        address seller;
        address token;
        uint256 tokenId;
        uint256 price;
        uint256 amount;
        bool active;
    }
    
    uint256 public listingCount;
    mapping(uint256 => Listing) public listings;
    
    event Listed(uint256 indexed id, address seller, uint256 price);
    event Purchased(uint256 indexed id, address buyer);
    event Cancelled(uint256 indexed id);
    
    constructor() Ownable(msg.sender) ${vibeMode ? '{\n        // Marketplace is live! 🚀' : '{'}
    }
    
    function createListing(
        address token,
        uint256 tokenId,
        uint256 price,
        uint256 amount
    ) external returns (uint256) {
        require(price > 0, "Price must be > 0");
        
        listingCount++;
        listings[listingCount] = Listing({
            seller: msg.sender,
            token: token,
            tokenId: tokenId,
            price: price,
            amount: amount,
            active: true
        });
        
        emit Listed(listingCount, msg.sender, price);
        return listingCount;
    }
    
    function purchaseListing(uint256 id) external payable {
        Listing storage listing = listings[id];
        require(listing.active, "Listing not active");
        require(msg.value >= listing.price, "Insufficient payment");
        
        listing.active = false;
        
        IERC1155(listing.token).safeTransferFrom(
            listing.seller,
            msg.sender,
            listing.tokenId,
            listing.amount,
            ""
        );
        
        payable(listing.seller).transfer(msg.value);
        
        emit Purchased(id, msg.sender);
    }
    
    function cancelListing(uint256 id) external {
        require(listings[id].seller == msg.sender, "Not seller");
        require(listings[id].active, "Already inactive");
        
        listings[id].active = false;
        emit Cancelled(id);
    }
}`;
  },
  auction: (description, vibeMode) => {
    const vibe = vibeMode ? `\n    // ⚡ Auction vibes! Time to bid! 💰\n    ` : '';
    return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC1155/IERC1155.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
${vibe}
/**
 * Auction Contract
 * ${description}
 * Generated by RealFlow Studio AI
 */
contract Auction is Ownable {
    struct AuctionItem {
        address seller;
        address token;
        uint256 tokenId;
        uint256 startingPrice;
        uint256 highestBid;
        address highestBidder;
        uint256 endTime;
        bool active;
    }
    
    uint256 public auctionCount;
    mapping(uint256 => AuctionItem) public auctions;
    
    event AuctionCreated(uint256 indexed id, address seller, uint256 startingPrice, uint256 endTime);
    event NewBid(uint256 indexed id, address bidder, uint256 amount);
    event AuctionEnded(uint256 indexed id, address winner, uint256 amount);
    
    constructor() Ownable(msg.sender) {}
    
    function createAuction(
        address token,
        uint256 tokenId,
        uint256 startingPrice,
        uint256 duration
    ) external returns (uint256) {
        auctionCount++;
        uint256 endTime = block.timestamp + duration;
        
        auctions[auctionCount] = AuctionItem({
            seller: msg.sender,
            token: token,
            tokenId: tokenId,
            startingPrice: startingPrice,
            highestBid: startingPrice,
            highestBidder: address(0),
            endTime: endTime,
            active: true
        });
        
        emit AuctionCreated(auctionCount, msg.sender, startingPrice, endTime);
        return auctionCount;
    }
    
    function placeBid(uint256 id) external payable {
        AuctionItem storage auction = auctions[id];
        require(auction.active, "Auction not active");
        require(block.timestamp < auction.endTime, "Auction ended");
        require(msg.value > auction.highestBid, "Bid too low");
        
        address previousBidder = auction.highestBidder;
        uint256 previousBid = auction.highestBid;
        
        auction.highestBidder = msg.sender;
        auction.highestBid = msg.value;
        
        if (previousBidder != address(0)) {
            payable(previousBidder).transfer(previousBid);
        }
        
        emit NewBid(id, msg.sender, msg.value);
    }
    
    function endAuction(uint256 id) external {
        AuctionItem storage auction = auctions[id];
        require(auction.active, "Already ended");
        require(block.timestamp >= auction.endTime, "Auction still active");
        
        auction.active = false;
        
        IERC1155(auction.token).safeTransferFrom(
            auction.seller,
            auction.highestBidder,
            auction.tokenId,
            1,
            ""
        );
        
        payable(auction.seller).transfer(auction.highestBid);
        
        emit AuctionEnded(id, auction.highestBidder, auction.highestBid);
    }
}`;
  },
  custom: (description, vibeMode) => {
    const vibe = vibeMode ? `\n    // 🎯 Custom contract mode - let's build something unique! 🌟\n    ` : '';
    return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC1155/ERC1155.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
${vibe}
/**
 * Custom RWA Contract
 * ${description}
 * Generated by RealFlow Studio AI
 */
contract CustomRWA is ERC1155, Ownable {
    address public treasury;
    uint256 public constant FEE_PERCENT = 250; // 2.5%
    
    mapping(address => bool) public operators;
    mapping(uint256 => string) public assetURIs;
    mapping(uint256 => uint256) public royalties;
    
    event AssetMinted(uint256 indexed id, address to, uint256 amount);
    event RoyaltySet(uint256 indexed id, uint256 percentage);
    
    constructor() ERC1155("") Ownable(msg.sender) {
        treasury = msg.sender;
        ${vibeMode ? '// Contract deployed - ready to mint some RWA! 🎉' : ''}
    }
    
    function setTreasury(address newTreasury) external onlyOwner {
        treasury = newTreasury;
    }
    
    function mintAsset(
        address to,
        uint256 id,
        uint256 amount,
        string memory uri,
        uint256 royaltyPercent
    ) external onlyOwner {
        require(bytes(uri).length > 0, "URI required");
        
        assetURIs[id] = uri;
        royalties[id] = royaltyPercent;
        _mint(to, id, amount, bytes(uri));
        
        emit AssetMinted(id, to, amount);
    }
    
    function getRoyalty(uint256 id) external view returns (uint256) {
        return royalties[id];
    }
    
    function uri(uint256 id) public view override returns (string memory) {
        return assetURIs[id];
    }
}`;
  }
};

function detectComponentsFromDescription(description) {
  const normalizedDesc = description.toLowerCase();
  const detectedComponents = [];
  
  for (const [componentType, info] of Object.entries(COMPONENT_INFO)) {
    for (const keyword of info.keywords) {
      if (normalizedDesc.includes(keyword)) {
        if (!detectedComponents.find(c => c.type === componentType)) {
          detectedComponents.push({
            type: componentType,
            name: info.name,
            confidence: 0.8
          });
        }
        break;
      }
    }
  }
  
  return detectedComponents;
}

function detectContractType(description) {
  const normalizedDesc = description.toLowerCase();
  
  if (normalizedDesc.includes("auction") || normalizedDesc.includes("bid")) {
    return "auction";
  }
  if (normalizedDesc.includes("marketplace") || normalizedDesc.includes("listing") || normalizedDesc.includes("sell")) {
    return "marketplace";
  }
  if (normalizedDesc.includes("token") || normalizedDesc.includes("nft") || normalizedDesc.includes("mint")) {
    return "token";
  }
  
  return "custom";
}

export async function generateCode({ description, contractType = 'custom', vibeMode = false }) {
  const openAiKey = process.env.OPENAI_API_KEY;
  
  const detectedType = contractType === 'custom' ? detectContractType(description) : contractType;
  const detectedComponents = detectComponentsFromDescription(description);
  
  if (!openAiKey || openAiKey === 'YOUR_API_KEY' || openAiKey === '') {
    console.log('No OpenAI key configured, using template');
    const templateFn = CONTRACT_TEMPLATES[detectedType] || CONTRACT_TEMPLATES.custom;
    return {
      code: templateFn(description, vibeMode),
      contractType: detectedType,
      components: detectedComponents,
      aiPowered: false
    };
  }

  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), 60000);

  try {
    const systemPrompt = `You are a Solidity smart contract expert for RealFlow Studio, a no-code platform for building RWA (Real World Asset) marketplaces.

Generate production-ready, secure Solidity code using OpenZeppelin contracts.
${vibeMode ? 'Add playful, fun comments with emojis to make the code more engaging!' : 'Use professional, clear comments.'}

For RWA (Real World Asset) marketplaces, always:
- Use ERC-1155 for fractional ownership
- Include proper access controls (Ownable)
- Add events for important state changes
- Use SafeMath or Solidity 0.8+ for overflow protection
- Follow Solidity naming conventions (mixedCase for functions, SCREAMING_SNAKE_CASE for constants)

Respond ONLY with valid Solidity code in a code block.`;

    const userPrompt = `Generate a ${detectedType} contract for RealFlow Studio marketplace:
${description}
${vibeMode ? '\nIMPORTANT: Add fun, playful comments with emojis throughout the code!' : ''}
Make it secure, gas-efficient, and production-ready.

The response should be ONLY the Solidity code in a markdown code block.`;

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${openAiKey}`
      },
      body: JSON.stringify({
        model: 'gpt-4-turbo-preview',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        max_tokens: 4000,
        temperature: vibeMode ? 0.9 : 0.7
      }),
      signal: controller.signal
    });

    clearTimeout(timeoutId);

    if (!response.ok) {
      const errorText = await response.text().catch(() => '');
      throw new Error(`OpenAI API error: ${response.status} ${response.statusText}`);
    }

    const data = await response.json();
    let generatedCode = data.choices[0]?.message?.content;
    
    if (!generatedCode) {
      throw new Error('No code generated from AI');
    }
    
    generatedCode = generatedCode.replace(/^```solidity\n?/, '').replace(/\n?```$/, '');
    
    return {
      code: generatedCode,
      contractType: detectedType,
      components: detectedComponents,
      aiPowered: true
    };
  } catch (error) {
    clearTimeout(timeoutId);
    if (error.name === 'AbortError') {
      console.log('AI request timed out, using template');
    } else {
      console.error('AI generation error:', error.message);
    }
    const templateFn = CONTRACT_TEMPLATES[detectedType] || CONTRACT_TEMPLATES.custom;
    return {
      code: templateFn(description, vibeMode),
      contractType: detectedType,
      components: detectedComponents,
      aiPowered: false
    };
  }
}

export async function optimizeCode({ code, optimizationType = 'all' }) {
  const openAiKey = process.env.OPENAI_API_KEY;
  
  const optimizationPrompts = {
    gas: {
      title: "Gas Optimization",
      focus: "Reduce gas costs by using memory instead of storage where possible, packing structs, using immutable for constants, etc."
    },
    security: {
      title: "Security Improvements",
      focus: "Add reentrancy guards, input validation, proper access controls, checks-effects-interactions pattern, etc."
    },
    readability: {
      title: "Code Readability",
      focus: "Add NatSpec comments, consistent naming conventions, proper spacing, modular functions, etc."
    },
    all: {
      title: "Full Optimization",
      focus: "Apply all optimizations: gas efficiency, security, and readability improvements."
    }
  };

  if (!openAiKey || openAiKey === 'YOUR_API_KEY' || openAiKey === '') {
    return {
      code: code,
      optimizationType,
      improvements: [`Applied ${optimizationPrompts[optimizationType]?.title || 'general'} suggestions`],
      aiPowered: false
    };
  }

  try {
    const systemPrompt = `You are a Solidity smart contract optimizer. Analyze and optimize the provided code for ${optimizationPrompts[optimizationType]?.title || 'general improvements'}.
${optimizationPrompts[optimizationType]?.focus}

Respond ONLY with the optimized Solidity code in a markdown code block.`;

    const userPrompt = `Optimize this Solidity code:\n\n${code}`;

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${openAiKey}`
      },
      body: JSON.stringify({
        model: 'gpt-4',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        max_tokens: 4000
      })
    });

    const data = await response.json();
    let optimizedCode = data.choices[0]?.message?.content;
    
    if (!optimizedCode) {
      return { code, optimizationType, improvements: [], aiPowered: false };
    }
    
    optimizedCode = optimizedCode.replace(/^```solidity\n?/, '').replace(/\n?```$/, '');
    
    return {
      code: optimizedCode,
      optimizationType,
      improvements: [`Applied ${optimizationPrompts[optimizationType]?.title || 'optimization'}`],
      aiPowered: true
    };
  } catch (error) {
    console.error('AI optimization error:', error);
    return { code, optimizationType, improvements: [], aiPowered: false };
  }
}

export async function analyzeCode({ code }) {
  const openAiKey = process.env.OPENAI_API_KEY;
  
  const analysis = {
    issues: [],
    suggestions: [],
    securityScore: 0,
    gasEstimate: "Unknown",
    lineCount: code.split('\n').length
  };
  
  if (!openAiKey || openAiKey === 'YOUR_API_KEY' || openAiKey === '') {
    if (code.includes('require(') && code.includes('onlyOwner')) {
      analysis.securityScore = 70;
      analysis.suggestions.push("Basic security checks present");
    }
    if (code.includes('emit ')) {
      analysis.suggestions.push("Events are being emitted");
    }
    if (code.includes('private') || code.includes('internal')) {
      analysis.suggestions.push("Visibility modifiers used");
    }
    return { ...analysis, aiPowered: false };
  }

  try {
    const systemPrompt = `You are a Solidity smart contract auditor. Analyze the provided code and return a JSON object with:
- issues: array of potential issues found
- suggestions: array of improvement suggestions
- securityScore: number from 0-100
- gasEstimate: string describing gas efficiency
- lineCount: number of lines

Be thorough and critical in your analysis.`;

    const userPrompt = `Analyze this Solidity code:\n\n${code}`;

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${openAiKey}`
      },
      body: JSON.stringify({
        model: 'gpt-4',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        max_tokens: 2000,
        response_format: { type: "json_object" }
      })
    });

    const data = await response.json();
    const analysisResult = JSON.parse(data.choices[0]?.message?.content || '{}');
    
    return { ...analysisResult, aiPowered: true };
  } catch (error) {
    console.error('AI analysis error:', error);
    return { ...analysis, aiPowered: false };
  }
}

export async function chat({ messages, vibeMode = false }) {
  const openAiKey = process.env.OPENAI_API_KEY;
  
  const defaultResponse = {
    content: "I'm here to help you build your RWA marketplace! Ask me about:\n- Smart contract generation\n- Component recommendations\n- Marketplace features\n- Gas optimization\n- Security best practices",
    suggestions: [
      "Generate a real estate token contract",
      "Add auction functionality",
      "Optimize gas usage",
      "Add fractional ownership"
    ],
    components: []
  };

  if (!openAiKey || openAiKey === 'YOUR_API_KEY' || openAiKey === '') {
    return { ...defaultResponse, aiPowered: false };
  }

  try {
    const systemPrompt = `You are an AI assistant for RealFlow Studio, a no-code platform for building RWA (Real World Asset) marketplaces on Polygon and Avalanche.

You help users:
- Generate smart contracts (tokens, marketplaces, auctions)
- Choose the right components for their marketplace
- Optimize gas usage
- Implement security best practices
- Understand blockchain concepts

${vibeMode ? 'Be playful and use emojis in your responses!' : 'Be professional and concise.'}

Keep responses helpful but not too long. When appropriate, suggest relevant marketplace components from: ${Object.values(COMPONENT_INFO).map(c => c.name).join(', ')}.`;

    const formattedMessages = messages.map(m => ({
      role: m.role,
      content: m.content
    }));

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${openAiKey}`
      },
      body: JSON.stringify({
        model: 'gpt-4-turbo-preview',
        messages: [
          { role: 'system', content: systemPrompt },
          ...formattedMessages
        ],
        max_tokens: 1500,
        temperature: vibeMode ? 0.9 : 0.7
      })
    });

    const data = await response.json();
    let content = data.choices[0]?.message?.content;
    
    if (!content) {
      return { ...defaultResponse, aiPowered: false };
    }
    
    const detectedComponents = detectComponentsFromDescription(content);
    
    return {
      content,
      suggestions: [],
      components: detectedComponents,
      aiPowered: true
    };
  } catch (error) {
    console.error('AI chat error:', error);
    return { ...defaultResponse, aiPowered: false };
  }
}

export async function getVibeSuggestion(theme) {
  const normalizedTheme = theme.toLowerCase().replace(/[^a-z]/g, '');
  const matchedTheme = Object.keys(VIBE_PROMPTS).find(
    key => normalizedTheme.includes(key) || key.includes(normalizedTheme)
  );
  
  return matchedTheme ? VIBE_PROMPTS[matchedTheme] : VIBE_PROMPTS.modern;
}
