import { useState } from "react";
import { Sparkles, Palette, Zap, Copy, Check, Loader2, Wand2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useAI, type AIMessage } from "@/hooks/useAI";
import { VIBE_THEMES } from "@/services/ai";

interface CreativeModeProps {
  onCodeGenerated?: (code: string) => void;
}

export function CreativeMode({ onCodeGenerated }: CreativeModeProps) {
  const [input, setInput] = useState("");
  const [selectedTheme, setSelectedTheme] = useState<keyof typeof VIBE_THEMES>("modern");
  const [copied, setCopied] = useState<string | null>(null);
  const [generatedCSS, setGeneratedCSS] = useState("");

  const { messages, loading, vibeMode, setVibeMode, sendMessage, getThemeSuggestion } = useAI({
    vibeMode: true,
    onCodeGenerated: onCodeGenerated,
  });

  const handleSend = async () => {
    if (!input.trim()) return;
    await sendMessage(input);
  };

  const handleThemeChange = async (theme: keyof typeof VIBE_THEMES) => {
    setSelectedTheme(theme);
    await getThemeSuggestion(theme);
  };

  const generateCSS = (theme: keyof typeof VIBE_THEMES) => {
    const themeData = VIBE_THEMES[theme];
    const css = `/* ${themeData.name} Theme - Generated by RealFlow Studio */
:root {
  --vibe-primary: ${themeData.colors[0]};
  --vibe-secondary: ${themeData.colors[1]};
  --vibe-accent: ${themeData.colors[2]};
  --vibe-background: ${themeData.colors[3]};
}

/* Apply vibes to your marketplace! 🚀 */
.vibe-container {
  background: linear-gradient(135deg, var(--vibe-primary), var(--vibe-secondary));
  color: var(--vibe-background);
}

/* This is your vibe, own it! 🔥 */
`;
    setGeneratedCSS(css);
  };

  const copyCode = (code: string, id: string) => {
    navigator.clipboard.writeText(code);
    setCopied(id);
    setTimeout(() => setCopied(null), 2000);
  };

  return (
    <div className="flex flex-col h-full">
      <div className="flex items-center gap-2 px-4 py-3 border-b border-border">
        <Sparkles className="w-4 h-4 text-primary" />
        <span className="font-semibold text-sm">Creative Mode</span>
        <button
          onClick={() => setVibeMode(!vibeMode)}
          className={`ml-auto text-xs px-2 py-0.5 rounded-full transition-colors ${
            vibeMode ? "bg-primary/10 text-primary" : "bg-secondary text-muted-foreground"
          }`}
        >
          {vibeMode ? "🔥 Creative" : "📝 Normal"}
        </button>
      </div>

      <Tabs defaultValue="chat" className="flex-1 flex flex-col">
        <TabsList className="w-full justify-start rounded-none border-b px-4 h-10">
          <TabsTrigger value="chat" className="text-xs gap-1">
            <Zap className="w-3 h-3" /> AI Chat
          </TabsTrigger>
          <TabsTrigger value="themes" className="text-xs gap-1">
            <Palette className="w-3 h-3" /> Themes
          </TabsTrigger>
        </TabsList>

        <TabsContent value="chat" className="flex-1 flex flex-col m-0">
          <div className="flex-1 overflow-y-auto p-4 space-y-4">
            {messages.map((m) => (
              <MessageBubble key={m.id} message={m} onCopy={copyCode} copied={copied} />
            ))}
            {loading && (
              <div className="flex items-center gap-2 text-sm text-muted-foreground">
                <Loader2 className="w-4 h-4 animate-spin" />
                {vibeMode ? "Vibing with code..." : "Generating..."}
              </div>
            )}
          </div>

          <div className="p-4 border-t border-border space-y-3">
            <div className="flex flex-wrap gap-2">
              {["Add royalty fees", "Real estate contract", "Auction logic", "Fractional shares"].map((s) => (
                <button
                  key={s}
                  onClick={() => sendMessage(s)}
                  disabled={loading}
                  className="shrink-0 text-xs px-3 py-1.5 rounded-full glass hover:border-primary/40 transition-colors disabled:opacity-50"
                >
                  {s}
                </button>
              ))}
            </div>
            <div className="flex gap-2">
              <input
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && handleSend()}
                placeholder="Describe what you want to build..."
                className="flex-1 bg-secondary rounded-lg px-3 py-2 text-sm placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
              />
              <Button size="sm" className="h-10 w-10 p-0" onClick={handleSend} disabled={loading}>
                <Zap className="w-4 h-4" />
              </Button>
            </div>
          </div>
        </TabsContent>

        <TabsContent value="themes" className="flex-1 overflow-y-auto m-0 p-4">
          <div className="space-y-4">
            <p className="text-sm text-muted-foreground">
              Choose a vibe for your marketplace! Each theme comes with custom colors and styling suggestions.
            </p>
            <div className="grid grid-cols-1 gap-3">
              {Object.entries(VIBE_THEMES).map(([key, theme]) => (
                <button
                  key={key}
                  onClick={() => handleThemeChange(key as keyof typeof VIBE_THEMES)}
                  className={`p-4 rounded-xl border transition-all text-left ${
                    selectedTheme === key
                      ? "border-primary bg-primary/5"
                      : "border-border hover:border-primary/40"
                  }`}
                >
                  <div className="flex items-center gap-3 mb-2">
                    <Wand2 className="w-4 h-4 text-primary" />
                    <span className="font-medium">{theme.name}</span>
                  </div>
                  <p className="text-xs text-muted-foreground mb-3">{theme.description}</p>
                  <div className="flex gap-2">
                    {theme.colors.map((color, i) => (
                      <div
                        key={i}
                        className="w-6 h-6 rounded-full border-2 border-background"
                        style={{ backgroundColor: color }}
                        title={color}
                      />
                    ))}
                  </div>
                </button>
              ))}
            </div>
            <Button
              className="w-full gap-2"
              onClick={() => generateCSS(selectedTheme)}
            >
              <Wand2 className="w-4 h-4" />
              Generate CSS for {VIBE_THEMES[selectedTheme].name}
            </Button>
            {generatedCSS && (
              <div className="relative group">
                <pre className="bg-background rounded-lg p-3 text-xs font-mono overflow-x-auto border">
                  <code>{generatedCSS}</code>
                </pre>
                <Button
                  size="sm"
                  variant="ghost"
                  className="absolute top-2 right-2 h-8 w-8 p-0"
                  onClick={() => copyCode(generatedCSS, "css")}
                >
                  {copied === "css" ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                </Button>
              </div>
            )}
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}

function MessageBubble({ message, onCopy, copied }: { message: AIMessage; onCopy: (code: string, id: string) => void; copied: string | null }) {
  return (
    <div className={`${message.role === "user" ? "ml-8" : "mr-4"}`}>
      <div className={`rounded-xl p-3 text-sm ${
        message.role === "user" ? "bg-primary/10 text-foreground" : "glass"
      }`}>
        {message.content}
      </div>
      {message.code && (
        <div className="mt-2 relative group">
          <pre className="bg-background rounded-lg p-3 text-xs font-mono overflow-x-auto border max-h-48 overflow-y-auto">
            <code>{message.code}</code>
          </pre>
          <Button
            size="sm"
            variant="ghost"
            className="absolute top-2 right-2 h-8 w-8 p-0 opacity-0 group-hover:opacity-100"
            onClick={() => onCopy(message.code!, message.id)}
          >
            {copied === message.id ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
          </Button>
        </div>
      )}
    </div>
  );
}

export default CreativeMode;
